int main()
{
   int k;
   try
   {
       k = 42;
   }
   catch (Exception)
   {
   }
   assert(true);
   return 0;
}
